site_name: Prakhyath's hive.

nav:
  - Home: 'index.md'
  - Notes: 'notes/notes_index.md'
  - ML-notes: 
    - mlNotes/mlNotes_index.md
    - Implementing Cyclic Learning rates in Kears: mlNotes/Implementing Cyclic Learning rates in Kears.md
  - About: 'about.md'

theme:

  name: material

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigatoion.expand
    - toc.follow
    # - navigation.top

  palette:

  # palette toggle for dark  mode
  - scheme: slate
    primary: black
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  #palette toggle for light mode
  - scheme: default
    primary: white
    toggle:  
      icon: material/brightness-7
      name: Switch to dark mode
markdown-extensions:
  - toc:
      permalink: true
      title: On this Page
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js